name: aquayar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.3
  country_picker: ^2.0.20
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^5.1.2
  logger: ^1.3.0
  meta: ^1.9.1
  path_provider: ^2.0.15
  searchbar_animation: ^0.0.4
  shared_preferences: ^2.1.1
  searchfield: ^0.8.3
  simple_gradient_text: ^1.2.4
  otp_text_field: ^1.1.3
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  internet_connection_checker: ^1.0.0+1
  geolocator: ^10.0.0
  json_serializable: ^6.7.0
  clay_containers: ^0.3.2
  flutter_polyline_points: ^1.0.0
  rflutter_alert: ^2.0.7
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.4.0
  http: ^0.13.6
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  uuid: ^3.0.7
  dartz: ^0.10.1
  smooth_page_indicator: ^1.1.0
  geocoding: ^2.1.0
  location: ^5.0.3
  web_socket_channel: ^2.4.0
  supabase: ^1.11.0
  supabase_flutter: ^1.10.13
  flutter_appauth: ^6.0.2
  crypto: ^3.0.3
  get_it: ^7.6.4
  flutter_paystack: ^1.0.7
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.3
  connectivity_plus: ^4.0.1
  hydrated_bloc: ^9.1.2
  socket_io_client: ^2.0.3+1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: neueplak

      fonts:
        - asset: assets/fonts/neueplak-Regular.ttf
